### ISSUE TITLE
Add primitives to support pre-fetching

### ISSUE THREAD

**Issue by ognen** [netceteragroup/girders-elements#25]
Apps may wish to anticipate what the user may click next and pre-fetch it in order to improve the perceived performance.

Add primitives to support such behavior. It may only be "cache warming" technique or something more  sophisticated (e.g. a stack-navigational element may want to preload and pre-render a number of pages in advance).

**Comment by andon** [comment]
I think with the current infrastructure we have (sub-systems, effects, zippers ...), such use-cases are doable fairly easy.

I've added an example (unit test + zipper helpers) in the following PR:
https://github.com/netceteragroup/girders-elements/pull/65

What do you think?

**Comment by ognen** [comment]
Yes, this issue is resolved. I would prefer if that test is converted into a doc page. The tests are really meant to coover our API contract and this one isn't covering much (except exposing the READ action... hmm, a yes, a test checking that the read actions are triggered may be a good idea but this is way too heavy).
