### ISSUE TITLE
Refactor and make clear/consistent usage of framework actions

### ISSUE THREAD

**Issue by andon** [netceteragroup/girders-elements#26]
At the moment we have several places where we dispatch actions that are generic and serve for a discrete problem.

One such group of actions are the actions used for our so-called reads:
https://github.com/netceteragroup/girders-elements/blob/master/src/read/reducer.js#L71

These are not at the moment clear, and can easy become conflicted with user-space actions. Reads for example, check that if an action begins with READ:
https://github.com/netceteragroup/girders-elements/blob/master/src/update/reducer.js#L32

This needs to be improved. Actions should follow the pragmatic practices, prefixing them like so:
`@@girders-elements/reads/READ_SUCCEEDED`

**Comment by ognen** [comment]
This is related to #10.

Declaring and namespacing such actions is a good idea.

**Comment by ognen** [comment]
With #60 it is now possible to register "stuff" for the empty kind (`[]`) as well. In the case of update / effects this would effectvely makes such an update / effect a global one -- it applies to all elements, as `isKindOf([], element) === true` for every element.

Will keep this open for the namespacing of reads.

**Comment by ognen** [comment]
With #66, this issue has been addressed.
