### ISSUE TITLE
Configuration of middlewares for the Engine

### ISSUE THREAD

**Issue by andon** [netceteragroup/girders-elements#28]
At the moment we only set the saga-middleware when bootstrapping the Engine.

We should have a clear way how we can set custom middlewares from app-space.

Very basic integration is done in the following commit (morpheus-branch):
https://github.com/netceteragroup/girders-elements/commit/2fa6f6f0aa859ff959e2e15b69443351b7720a19

**Comment by andon** [comment]
@ognen Shall we close this now?

**Comment by ognen** [comment]
Yes.

On Apr 12, 2017, at 11:51, Andon Sikavica <notifications@github.com<mailto:notifications@github.com>> wrote:


@ognen<https://github.com/ognen> Shall we close this now?

-
