### ISSUE TITLE
Add support for transformers

### ISSUE THREAD

**Issue by ognen** [netceteragroup/girders-elements#31]
Users should be able to register transformers per element kind

    transformers.register(['el', 'kind'], (el, root) => el)

The transformer gets the current element as well as the root of the transformed 'document', returns the modified version of the element. 

Think about the following:
- are transformers registered globally or just for specific reads?
- what specifically should the root object be

**Comment by vule-rng** [comment]
@ognen, @bPopovska, @andon 
- "are transformers registered globally or just for specific reads" - we had a case where we needed to apply a transformer on the cached state (no __read). 
-"what specifically should the root object be" - I can't think of any reason why we would go above the scene/page in the state. We shouldn't co down to scene/page content if we need page/scene metadata as an additional object in the scene (not first element).

**Comment by ognen** [comment]
- they are global registered and applied only when data enters the sysetms
- reading from a cache is also a read
- the root object is the thing that you read from the server (i.e. the response); it is up to you to define it. Reads do not necessarily read only pages, they may read multiple pages at once or just a fragment of a page (that needs a lot of time)
- finally, scenes and pages aren't concepts defined at the level of Girders Elements ;)
