### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by andon** [netceteragroup/girders-elements#50]
![screen shot 2017-07-13 at 14 45 53](https://user-images.githubusercontent.com/1130655/28167098-a64eb2b4-67da-11e7-9b4d-17d897b38fa1.png)

If you ran the project on iOS 8, and most of the Android OSs (tested on Android 7.0), you will run into this issue.

This is due to the fact, that `Symbol` is not supported with the JavaScriptCore that comes with those OSs. This was not fixed in the react-native to be properly polyfilled for all supported platforms (iOS 8 and above, Android 4.1 and above as stated in RN README.md).

Solution should be to include either the `babel-polyfill` or parts of `core-js` in the root of the application files (`index.ios.js`, `index.android.js`):
```
import 'babel-polyfill'
// or
import 'core-js/modules/es6.symbol';
```

Shell we document this requirement?

Is there a eslint rule that might catch usage of those, so that we can check them?

Example, for Android, in one project we needed to also import some of the core data structure, having the following at the top of `index.android.js`:
```
import 'core-js/modules/es6.symbol';
import 'core-js/modules/es6.set';
import 'core-js/modules/es6.map';
import 'core-js/modules/es6.weak-map';
import 'core-js/modules/es6.weak-set';
```

**Comment by andon** [comment]
Related: https://github.com/facebook/react-native/issues/4676

**Comment by ognen** [comment]
Changed the use of Symbols to namespaced property names in #60
