### ISSUE TITLE
Switch to ramda

### ISSUE THREAD

**Issue by ognen** [netceteragroup/girders-elements#6]
We rely on immutable for the application state. However, we need a good utility belt library for handling plain JS objects. 

We used lodash until now, but perhaps we should swith to ramda as it has a more functional  interface (with curried functions by default as well as parameter omissions).

Should we drop lodash and switch to ramda? Ramda has more functional-style. @andon what say you?

**Comment by andon** [comment]
Yes, sure. We anyway don't have many places where we use lodash at the moment.

The question is if we should go with ramda or lodash-fp. I guess any of them would suffice.

Even though you suggest that we should look into utility lib for handling plain JS object, I think it might be better to try to also use the same lib to help with immutables as well. Seems that ramda has more traction in that direction, so we can go with it.

https://medium.com/@drboolean/lenses-with-immutable-js-9bda85674780

**Comment by ognen** [comment]
Re. Lenses, they are quite useful when drilling down the application state, but they don't allow you to  up the tree like [zippers](https://github.com/tommikaikkonen/zippa) do.  In  any case, ramda seems to offer good support for fp style work.
